#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Silly\Application;
use BeyondCode\LaravelPackageTools\Commands\MakeCommand;
use BeyondCode\LaravelPackageTools\Commands\MakeRequest;
use BeyondCode\LaravelPackageTools\Commands\MakeJob;
use BeyondCode\LaravelPackageTools\Commands\MakeEvent;
use BeyondCode\LaravelPackageTools\Commands\MakeNotification;
use BeyondCode\LaravelPackageTools\Commands\MakeRule;
use BeyondCode\LaravelPackageTools\Commands\MakeMigration;
use BeyondCode\LaravelPackageTools\Commands\MakeFactory;
use BeyondCode\LaravelPackageTools\Commands\MakeModel;

$version = '1.0.0';

$app = new Application('Laravel Package Tools', $version);

$app->command('make:command name [--command=] [--force]', new MakeCommand);
$app->command('make:request name [--force]', new MakeRequest);
$app->command('make:job name [--sync] [--force]', new MakeJob);
$app->command('make:event name [--force]', new MakeEvent);
$app->command('make:notification name [--force]', new MakeNotification);
$app->command('make:rule name [--force]', new MakeRule);
$app->command('make:migration name [--create=] [--force]', new MakeMigration);
$app->command('make:factory name [--model=] [--force]', new MakeFactory);
$app->command('make:model name [--m|migration] [--f|factory] [--force]', new MakeModel);

$app->run();